# Generated by Django 3.1 on 2020-08-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('edad', models.IntegerField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
            ],
        ),
    ]
